image: alpine/edge
packages:
  - python3
  - py3-pip
  - py3-flit
sources:
  - https://git.sr.ht/~rasch/unzippy
environment:
  project: unzippy
  FLIT_USERNAME: __token__
secrets:
  - 2681cfa1-b878-4070-84d5-cc8e8e4dd529 # PyPI token (FLIT_PASSWORD)
tasks:
  - stop_if_not_release: |
      cd "$project"
      git describe --exact-match HEAD || complete-build
  - publish: |
      cd "$project"
      set +x
      . ~/.env
      set -x
      flit publish
